apiVersion: v1
kind: Service
metadata:
  name: fulfillment
  labels:
    app: fulfillment
spec:
  type: ClusterIP
  selector:
    app: fulfillment
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
