apiVersion: v1
kind: Service
metadata:
  name: batching
  labels:
    app: batching
spec:
  type: ClusterIP
  selector:
    app: batching
  ports:
    - name: grpc
      port: 50052
      targetPort: grpc
